name: Publish

on:
  schedule:
    - cron:  '5 0 * * *'
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: ''
        default: patch
        options:
          - major
          - minor
          - patch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: josa42/actions/npm-publish@main
        with:
          version: '${{ inputs.version }}'
          npm-token: '${{ secrets.NPM_TOKEN }}'

