name: Publish

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: ''
        default: patch
        options:
          - major
          - minor
          - patch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm version "${{ inputs.version || 'patch' }}"
      - run: npm run build
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
      - run: npm publish --dry-run
      - run: npm view coc-go
      - id: dist-check
        name: check if has changes
        run: |
          head_sha="$(npm publish --dry-run --json 2>/dev/null | jq -r .shasum)"
          dist_sha="$(npm view coc-go --json | jq -r .dist.shasum)"

          echo "$head_sha == $dist_sha"

          if [[ "$head_sha" == "$dist_sha" ]]; then
            echo "::notice::No change since last published version"
            echo "has-changes=false" >> "$GITHUB_OUTPUT"
          else
            echo "has-changes=true" >> "$GITHUB_OUTPUT"
          fi

      - if: steps.dist-check.outputs.has-changes == 'true'
        run: npm run test

      - if: steps.dist-check.outputs.has-changes == 'true'
        run: npm publish

      - if: steps.dist-check.outputs.has-changes == 'true'
        run: git push origin HEAD:master --follow-tags


