name: Settings

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: josa42/actions/update@main
        with:
          run-update: |
            ./scripts/update-commands.js
            ./scripts/update-options.js
            ./scripts/update-options-interface.js
            ./scripts/update-snippets.js
            ./scripts/update-tables.sh
          run-tests: |
            npm ci
            npm run build
            npm run lint
            npm run test
